description: qlora_alpaca

target:
  service: aml
  # name: tscience-a100-80g-eastus
  name: A100-80G-PCIE-westus3
  # name: V10032G
  # name: A100EastUS
  # name: openai-A10080G
  # name: A10080G
  # name: gpu-v100-32g
  # name: gpu-a100-80g


environment:
  image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
  image_setup:
    - apt-get -y update
    - apt-get -y install wget
    - apt-get -y install git
  setup:
    - pip install transformers
    - pip install git+https://github.com/huggingface/accelerate
    - pip install evaluate scikit-learn scipy typing_extensions einops
    - pip install datasets sentencepiece setuptools rouge-score nltk openai
    - pip install tensorboard tensorboardX

storage:
  output:
    storage_account_name: tsinterns
    container_name: t-qingru
    mount_dir: /mnt/t-qingru

code:
  local_dir: ../

jobs:
- name: qlora_alpaca_bit2
  sku: 1xG4
  process_count_per_node: 1
  submit_args:
    container_args:
      cpus: 32
  command:
    - python train.py --num_bits 2 --num_iter 1 --reduced_rank 8 --learning_rate 1e-4 --seed 42 --model_name_or_path meta-llama/Llama-2-7b-hf --data_path ./alpaca_data.json --output_dir /mnt/t-qingru/qqlora/exp_results --num_train_epochs 3 --per_device_train_batch_size 16 --per_device_eval_batch_size 16 --gradient_accumulation_steps 2 --evaluation_strategy "steps" --save_strategy "steps" --save_steps 2000 --save_total_limit 1 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type "cosine" --logging_steps 1 --path_to_model_zoo /mnt/t-qingru/yixiao_model_zoo
    - python train.py --num_bits 2 --num_iter 1 --reduced_rank 8 --learning_rate 3e-4 --seed 42 --model_name_or_path meta-llama/Llama-2-7b-hf --data_path ./alpaca_data.json --output_dir /mnt/t-qingru/qqlora/exp_results --num_train_epochs 3 --per_device_train_batch_size 16 --per_device_eval_batch_size 16 --gradient_accumulation_steps 2 --evaluation_strategy "steps" --save_strategy "steps" --save_steps 2000 --save_total_limit 1 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type "cosine" --logging_steps 1 --path_to_model_zoo /mnt/t-qingru/yixiao_model_zoo
    - python train.py --num_bits 2 --num_iter 0 --reduced_rank 8 --learning_rate 1e-4 --seed 42 --model_name_or_path meta-llama/Llama-2-7b-hf --data_path ./alpaca_data.json --output_dir /mnt/t-qingru/qqlora/exp_results --num_train_epochs 3 --per_device_train_batch_size 16 --per_device_eval_batch_size 16 --gradient_accumulation_steps 2 --evaluation_strategy "steps" --save_strategy "steps" --save_steps 2000 --save_total_limit 1 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type "cosine" --logging_steps 1 --path_to_model_zoo /mnt/t-qingru/yixiao_model_zoo
    - python train.py --num_bits 2 --num_iter 0 --reduced_rank 8 --learning_rate 3e-4 --seed 42 --model_name_or_path meta-llama/Llama-2-7b-hf --data_path ./alpaca_data.json --output_dir /mnt/t-qingru/qqlora/exp_results --num_train_epochs 3 --per_device_train_batch_size 16 --per_device_eval_batch_size 16 --gradient_accumulation_steps 2 --evaluation_strategy "steps" --save_strategy "steps" --save_steps 2000 --save_total_limit 1 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type "cosine" --logging_steps 1 --path_to_model_zoo /mnt/t-qingru/yixiao_model_zoo
